server:
  port: 8081

spring:
  application:
    name: auth-service
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        deregister: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-timeout: 5s
        register-health-check: true
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: "youraveryasecureaandarandoma32abytesalongasecretakey"
  expiration: 3600000 # 1 hour in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  security:
    enabled: false  # Disable security for Actuator



