server:
  port: 8082

spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:postgresql://postgres-storage:5432/storage_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-timeout: 5s
        register-health-check: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    root: INFO
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.consul: ERROR

